ORB_SLAM3_RGBD_ROS2:
  ros__parameters:
    robot_base_frame: base_footprint
    global_frame: map
    odom_frame: odom
    # robot_namespace: summit
    robot_x: 1.0
    robot_y: 1.0
    visualization: true
    ros_visualization: false